### ISSUE TITLE
JS script

### ISSUE THREAD

**Issue by safronik** [Glomberg/ip-validator#1]
Hello,

Isn't it better to use wp_enqueue_script function to attach the script instead of doing it inline?

Why your JS file has .inc exstension?

**Comment by Glomberg** [comment]
Hi @safronik ,

I've included my js inline because I want to show this code only for opened comment form. If I would attached it by wp_enqueue_script() this script would be shown regardless of presence of contact form on the page. Sure I would can added some logic for wp_enqueue_script() action. But I decided not to do it.

My JS code moved separately from php code. The extension of the file does not have any importance. .inc says it is a included file.
